#include <exception>

int add(const char* input) {
  throw std::exception();
}
